name: CI/CD - Flask Task Manager

on:
  push:
    branches: [ "main" ]  # Runs when pushing to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Build & Push Docker Image to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/flask-task-manager:latest
        docker build -t $IMAGE .
        docker push $IMAGE

    # Deploy on EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-task-manager:latest
          sudo docker stop flask-task-manager || true
          sudo docker rm flask-task-manager || true
          sudo docker run -d -p 80:5000 --name flask-task-manager ${{ secrets.DOCKERHUB_USERNAME }}/flask-task-manager:latest
